DROP TABLE IF EXISTS dino;

CREATE TABLE dino (
	id		INTEGER PRIMARY KEY AUTOINCREMENT,
	name		TEXT UNIQUE NOT NULL,
	img		TEXT,
	parent_id	INTEGER,

	FOREIGN KEY (parent_id) REFERENCES dino (id)
);


DROP TABLE IF EXISTS content;

CREATE TABLE content (
	id		INTEGER PRIMARY KEY AUTOINCREMENT,
	title		TEXT,
	text		TEXT NOT NULL,
	dino_id		INTEGER NOT NULL,

	FOREIGN KEY (dino_id) REFERENCES dino (id)
);
